title: MLSA GitHub Pages Workshop
theme: minima
author: Manish Kumar Barnwal
email: manish.barnwal@studentambassadors.com
description: >
  This is a website to shoutout participants who participated in the "MLSA GitHub Pages Workshop".
twitter_username: imanishbarnwal
github_username:  imanishbarnwal